---
title: "Generalization & transfer paper"
output: html_notebook
---


```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
```

```{r}
theme_set(theme_bw(base_size = 15) +
            theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()))
```


## Assumption checks
```{r}
nruns = 5
noise_vars = c(1.)
output_sizes= c(100)
svms = 1:10
alignments = c("True", "False")
d = data.frame()
for (noise_var in noise_vars) {
  for (output_size in output_sizes) {
    for (svm in svms) {
      for (aligned in alignments) {
        for (run in 0:(nruns-1)) { 
          this_d = read.csv(sprintf("../single_generalization_comparison_results/noise_var_%.2f_output_size_%i_svm_%f_aligned_%s_run_%i.csv",noise_var, output_size, svm, aligned, run), header=T)
    
          this_d = this_d %>% 
            mutate(noise_var=noise_var, output_size=output_size, svm=svm, aligned=aligned=="True", run=run, student_rank="Full rank", type="Empirical")
          d = bind_rows(d, this_d)
        }
      }
      this_d = read.csv(sprintf("../single_generalization_comparison_results/noise_var_%.2f_svm_%f_theory_track.csv", noise_var, svm), header=T)
    
      this_d = this_d %>% 
        rename(loss=generalization_error) %>%
        mutate(noise_var=noise_var, output_size=NA,  svm=svm, aligned=aligned=="True", run=NA, student_rank="Full rank", type="Theory")
      d = bind_rows(d, this_d)
    }
  }
}
```

```{r}
prepostfix = "rank4stud"
for (noise_var in noise_vars) {
  for (output_size in output_sizes) {
    for (svm in svms) {
      for (aligned in alignments) {
        for (run in 0:(nruns-1)) { 
          this_d = read.csv(sprintf("../single_generalization_comparison_results_%s/noise_var_%.2f_output_size_%i_svm_%f_aligned_%s_run_%i.csv", prepostfix, noise_var, output_size, svm, aligned, run), header=T)
    
          this_d = this_d %>% 
            mutate(noise_var=noise_var, output_size=output_size, svm=svm, aligned=aligned=="True", student_rank="4% of full", run=run, type="Empirical")
          d = bind_rows(d, this_d)
        }
      }
      this_d = read.csv(sprintf("../single_generalization_comparison_results_%s/noise_var_%.2f_svm_%f_theory_track.csv", prepostfix, noise_var, svm), header=T)
    
      this_d = this_d %>% 
        rename(loss=generalization_error) %>%
        mutate(noise_var=noise_var, output_size=NA,  svm=svm, aligned=aligned=="True", run=NA,  student_rank="4% of full", type="Theory")
      d = bind_rows(d, this_d)
    }
  }
}
```

```{r}
prepostfix = "smallstud"
for (noise_var in noise_vars) {
  for (output_size in output_sizes) {
    for (svm in svms) {
      for (aligned in alignments) {
        for (run in 0:(nruns-1)) { 
          this_d = read.csv(sprintf("../single_generalization_comparison_results_%s/noise_var_%.2f_output_size_%i_svm_%f_aligned_%s_run_%i.csv", prepostfix, noise_var, output_size, svm, aligned, run), header=T)
    
          this_d = this_d %>% 
            mutate(noise_var=noise_var, output_size=output_size, svm=svm, aligned=aligned=="True", student_rank="Teacher rank (1% of full)", run=run, type="Empirical")
          d = bind_rows(d, this_d)
        }
      }
      this_d = read.csv(sprintf("../single_generalization_comparison_results_%s/noise_var_%.2f_svm_%f_theory_track.csv", prepostfix, noise_var, svm), header=T)
    
      this_d = this_d %>% 
        rename(loss=generalization_error) %>%
        mutate(noise_var=noise_var, output_size=NA,  svm=svm, aligned=aligned=="True", run=NA,  student_rank="Teacher rank (1% of full)", type="Theory")
      d = bind_rows(d, this_d)
    }
  }
}
```

```{r}
prepostfix = "50stud"
for (noise_var in noise_vars) {
  for (output_size in output_sizes) {
    for (svm in svms) {
      for (aligned in alignments) {
        for (run in 0:(nruns-1)) { 
          this_d = read.csv(sprintf("../single_generalization_comparison_results_%s/noise_var_%.2f_output_size_%i_svm_%f_aligned_%s_run_%i.csv", prepostfix, noise_var, output_size, svm, aligned, run), header=T)
    
          this_d = this_d %>% 
            mutate(noise_var=noise_var, output_size=output_size, svm=svm, aligned=aligned=="True", student_rank="50% of full", run=run, type="Empirical")
          d = bind_rows(d, this_d)
        }
      }
      this_d = read.csv(sprintf("../single_generalization_comparison_results_%s/noise_var_%.2f_svm_%f_theory_track.csv", prepostfix, noise_var, svm), header=T)
    
      this_d = this_d %>% 
        rename(loss=generalization_error) %>%
        mutate(noise_var=noise_var, output_size=NA,  svm=svm, aligned=aligned=="True", run=NA,  student_rank="50% of full", type="Theory")
      d = bind_rows(d, this_d)
    }
  }
}
```

```{r}
d = d %>%
  mutate(output_size=factor(output_size),
         noise_var=factor(noise_var),
         svm=factor(svm),
         aligned=factor(aligned),
         type=factor(type),
         student_rank=factor(student_rank, levels=c("Full rank", "50% of full", "4% of full", "Teacher rank (1% of full)"), labels=c("Full rank", "50% of full", "4% of full", "1% of full")),
         log_loss = log(loss))
```

```{r}
min_d = d %>%
  group_by(svm, aligned, noise_var, type, student_rank, run) %>%
  summarize(min_Eg = min(log_loss), min_t = which.min(log_loss)) %>%
  ungroup() %>%
  group_by(svm, aligned, noise_var, student_rank, type) %>%
  summarize(avg_min_Eg = mean(min_Eg), sd_min_Eg = sd(min_Eg),
            avg_min_t = mean(min_t), sd_min_t = sd(min_t),
            se_min_Eg = sd_min_Eg/sqrt(n()), ci_Eg_up= avg_min_Eg + 1.96*se_min_Eg, ci_Eg_lo= avg_min_Eg - 1.96*se_min_Eg,
            se_min_t = sd_min_t/sqrt(n()), ci_t_up= avg_min_t + 1.96*se_min_t, ci_t_lo= avg_min_t - 1.96*se_min_t) %>%
  ungroup()
  
```

```{r}
avg_d = d %>%
  group_by(noise_var, output_size, svm, aligned, epoch, student_rank, type) %>%
  summarize(loss=mean(loss), log_loss_sd=sd(log_loss), log_loss=mean(log_loss)) %>%
  mutate(log_loss_95_low=log_loss-1.96*log_loss_sd/sqrt(n()), log_loss_95_high=log_loss+1.96*log_loss_sd/sqrt(n())) %>%
  ungroup() %>%
  mutate(new_type = ifelse(type == "Theory", "Theory",
                            ifelse(aligned == "TRUE", "Empirical aligned", "Empirical random"))) %>%
  mutate(new_type = factor(new_type, levels=c("Theory", "Empirical aligned", "Empirical random")))
```


```{r}
# ggplot(avg_d, aes(x=epoch, y=log_loss, color=as.numeric(svm), shape=student_rank, group=interaction(new_type, svm, student_rank))) +
#   geom_line(size=1.2) +
# #  geom_ribbon(aes(ymin=log_loss_95_low, ymax=log_loss_95_high, fill=features), alpha=0.5) +
#   scale_color_gradient(low="#0000FF", high="#FF0000") +
#   ylab("Log generalization loss") +
#   xlab("Epoch") +
#   guides(color=guide_colorbar(title="SNR"), linetype=guide_legend(title="Theory or empirical"))
```

```{r}
# ggsave(sprintf("../plots/%s_theory_empirical_alignment.png", prepostfix))
```
```{r}
wide_min_d = min_d %>% 
  filter(type == "Empirical") %>%
  select(-type, -se_min_Eg, -se_min_t) %>%
  gather(metric, measurement, avg_min_Eg, sd_min_Eg, avg_min_t, sd_min_t, ci_t_up, ci_t_lo, ci_Eg_up, ci_Eg_lo) %>%
  mutate(aligned = ifelse(aligned=="TRUE", "Aligned", "Random")) %>%
  unite(am, aligned, metric) %>%
  spread(am, measurement) %>%
  filter(svm != 1)
```


```{r}
ggplot(data=wide_min_d, aes(x=Aligned_avg_min_Eg, y=Random_avg_min_Eg, shape=student_rank, color=as.numeric(svm))) +
  scale_color_gradient(low="#0000FF", high="#FF0000", limits=c(1, 10), breaks=c(1, 10))  +
  geom_abline(aes(intercept=0, slope=1), alpha=0.5, linetype=3) +
  labs(x="Min log generalization error (aligned init.)",
       y="Min log generalization error (random init.)") +
  geom_point(size=2) +
  geom_errorbar(aes(ymin=Random_ci_Eg_lo, ymax=Random_ci_Eg_up), width=0.05) +
  geom_errorbarh(aes(xmin=Aligned_ci_Eg_lo, xmax=Aligned_ci_Eg_up), height=0.05) +
  guides(color=F, shape=F)
```

```{r}
ggsave("../plots/paper/min_Eg_aligned_vs_random.png", width=5, height=5)
```

```{r}

```


```{r}
ggplot(data=wide_min_d, aes(x=Aligned_avg_min_t, y=Random_avg_min_t, shape=student_rank, color=as.integer(svm))) +
  scale_color_gradient(low="#0000FF", high="#FF0000", limits=c(1, 10), breaks=c(1,10))  +
  geom_abline(aes(intercept=0, slope=1), alpha=0.5, linetype=3) +
  labs(x="Optimal stopping epoch (aligned init.)",
       y="Optimal stopping epoch (random init.)") +
  geom_point(size=2) +
  geom_errorbar(aes(ymin=Random_ci_t_lo, ymax=Random_ci_t_up), width=5) +
  geom_errorbarh(aes(xmin=Aligned_ci_t_lo, xmax=Aligned_ci_t_up), height=5) +
  xlim(200, 800) + 
  ylim(200, 800) +
  guides(shape=guide_legend(title="Empirical results", order=2), color=guide_colorbar(title="SNR", order=1))
```

```{r}
ggsave("../plots/paper/min_t_aligned_vs_random.png", width=7, height=5)
```

```{r}
min_d2 = min_d %>% 
  mutate(this_type=ifelse(type=="Theory", "Theory",
                          ifelse(aligned == "TRUE", "Empirical-aligned", "Empirical-random"))) %>%
  select(-type, -aligned, -se_min_Eg, -se_min_t) 
```

```{r}
ggplot(data=min_d2 %>% filter(this_type=="Empirical-aligned", svm != 1), aes(x=avg_min_t, y=avg_min_Eg, color=as.integer(svm), shape=student_rank)) +
  scale_color_gradient(low="#0000FF", high="#FF0000", limits=c(1, 10), breaks=c(1,10))  +
#  geom_abline(aes(intercept=0, slope=1), alpha=0.5, linetype=3) +
  geom_line(data= min_d2 %>% filter(this_type=="Theory", svm != 1), aes(group=student_rank, linetype=this_type))+ 
  labs(x="Optimal stopping epoch",
       y="Best log generalization error") +
  geom_point(size=2) +
#  geom_errorbar(aes(ymin=ci_Eg_lo, ymax=ci_Eg_up), width=7) +
#  geom_errorbarh(aes(xmin=ci_t_lo, xmax=ci_t_up), height=0.05) +
  ylim(-4, 0) +
  xlim(150, 800) +
  guides(shape=guide_legend(title="Empirical results", order=2), color=guide_colorbar(title="SNR", order=1), linetype=guide_legend(title="", order=3))
```

```{r}
ggsave("../plots/paper/aligned_min_Eg_vs_min_t.png", width=7, height=5)
```


```{r}
ggplot(data=min_d2 %>% filter(this_type=="Empirical-random", svm != 1), aes(x=avg_min_t, y=avg_min_Eg, color=as.integer(svm), shape=student_rank)) +
  scale_color_gradient(low="#0000FF", high="#FF0000", limits=c(1, 10), breaks=c(1,10))  +
#  geom_abline(aes(intercept=0, slope=1), alpha=0.5, linetype=3) +
#  geom_line(data= min_d2 %>% filter(this_type=="Theory", svm != 1), aes(group=student_rank, linetype=this_type))+ 
  labs(x="Optimal stopping epoch",
       y="Best log generalization error") +
  geom_point(size=2) +
#  geom_errorbar(aes(ymin=ci_Eg_lo, ymax=ci_Eg_up), width=7) +
#  geom_errorbarh(aes(xmin=ci_t_lo, xmax=ci_t_up), height=0.05) +
  ylim(-4, 0) +
  xlim(150, 800) +
  guides(color=F, shape=F)
```

```{r}
ggsave("../plots/paper/random_min_Eg_vs_min_t.png", width=5, height=5)
```

# Approximating min generalization error with only components out of the noise and misalignment

```{r}
approx_min_d = bind_rows(
  read.csv("../single_generalization_comparison_results/min_gen_approx.csv") %>%
    mutate(student_rank="Full rank"),
  read.csv("../single_generalization_comparison_results_rank4stud/min_gen_approx.csv") %>%
    mutate(student_rank="4% of full"),
  read.csv("../single_generalization_comparison_results_50stud/min_gen_approx.csv") %>%
    mutate(student_rank="50% of full"),
  read.csv("../single_generalization_comparison_results_smallstud/min_gen_approx.csv") %>%
    mutate(student_rank="Teacher rank (1% of full)"))

```

```{r}
approx_min_d = approx_min_d %>% 
  rename(svm=singular_value_multiplier) %>%
  mutate(approx_log_eg = log(approx_eg),
         svm=factor(svm),
         student_rank=factor(student_rank, levels=c("Full rank", "50% of full", "4% of full", "Teacher rank (1% of full)"), labels=c("Full rank", "50% of full", "4% of full", "1% of full")))
```

```{r}
approx_min_d = inner_join(approx_min_d, wide_min_d)
```

```{r}
ggplot(data=approx_min_d, aes(x=Aligned_avg_min_Eg, y=approx_log_eg, color=as.integer(svm), shape=student_rank)) +
  scale_color_gradient(low="#0000FF", high="#FF0000", limits=c(1, 10), breaks=c(1,10))  +
  labs(x="Empirical best log testing error (aligned init)",
       y="Simple approx. to best log test error") +
  geom_abline(aes(intercept=0, slope=1), alpha=0.5, linetype=3) +
  geom_errorbarh(aes(xmin=Aligned_ci_Eg_lo, xmax=Aligned_ci_Eg_up), height=0.05) +
  guides(shape=guide_legend(title="Empirical results", order=2), color=guide_colorbar(title="SNR", order=1)) +
  geom_point(size=2) 
```
```{r}
ggsave("../plots/paper/simple_min_test_error_approx_aligned.png")
```


```{r}
ggplot(data=approx_min_d, aes(x=Random_avg_min_Eg, y=approx_log_eg, color=as.integer(svm), shape=student_rank)) +
  scale_color_gradient(low="#0000FF", high="#FF0000", limits=c(1, 10), breaks=c(1,10))  +
  labs(x="Empirical best log testing error (random init)",
       y="Simple approx. to best log test error") +
  geom_abline(aes(intercept=0, slope=1), alpha=0.5, linetype=3) +
  geom_errorbarh(aes(xmin=Random_ci_Eg_lo, xmax=Random_ci_Eg_up), height=0.05) +
  guides(shape=guide_legend(title="Empirical results", order=2), color=guide_colorbar(title="SNR", order=1)) +
  geom_point(size=2) 
```
```{r}
ggsave("../plots/paper/simple_min_test_error_approx_random.png")
```